---
  - hosts: all
    any_errors_fatal: true
    name: Remove Old Kismatic Packages
    become: yes
    vars_files:
      - group_vars/all.yaml
  
    environment:
      https_proxy: "{{ https_proxy }}"
      http_proxy: "{{ http_proxy }}"
      no_proxy: "{{ no_proxy }}"  

    roles:
      - role: packages-cleanup
