---
  - hosts: all
    any_errors_fatal: true
    name: Run Upgrade Pre-Flight Checks
    become: yes
    vars_files:
      - group_vars/all.yaml
    roles:
      - upgrade-preflight
    environment:
      https_proxy: "{{ https_proxy }}"
      http_proxy: "{{ http_proxy }}"
      no_proxy: "{{ no_proxy }}"